// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Settings.proto

package com.proto.settings;

public final class SettingsProto {
  private SettingsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProfileListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:modpack.ProfileList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    java.util.List<com.proto.settings.SettingsProto.ProfileList.Profile> 
        getProfilesList();
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    com.proto.settings.SettingsProto.ProfileList.Profile getProfiles(int index);
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    int getProfilesCount();
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    java.util.List<? extends com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder> 
        getProfilesOrBuilderList();
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder getProfilesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code modpack.ProfileList}
   */
  public  static final class ProfileList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:modpack.ProfileList)
      ProfileListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProfileList.newBuilder() to construct.
    private ProfileList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProfileList() {
      profiles_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.settings.SettingsProto.ProfileList.class, com.proto.settings.SettingsProto.ProfileList.Builder.class);
    }

    public interface ProfileOrBuilder extends
        // @@protoc_insertion_point(interface_extends:modpack.ProfileList.Profile)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string minecraftPath = 2;</code>
       */
      java.lang.String getMinecraftPath();
      /**
       * <code>string minecraftPath = 2;</code>
       */
      com.google.protobuf.ByteString
          getMinecraftPathBytes();

      /**
       * <code>string selectedModpack = 3;</code>
       */
      java.lang.String getSelectedModpack();
      /**
       * <code>string selectedModpack = 3;</code>
       */
      com.google.protobuf.ByteString
          getSelectedModpackBytes();

      /**
       * <code>bool replace = 4;</code>
       */
      boolean getReplace();
    }
    /**
     * Protobuf type {@code modpack.ProfileList.Profile}
     */
    public  static final class Profile extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:modpack.ProfileList.Profile)
        ProfileOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Profile.newBuilder() to construct.
      private Profile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Profile() {
        name_ = "";
        minecraftPath_ = "";
        selectedModpack_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_Profile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_Profile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.settings.SettingsProto.ProfileList.Profile.class, com.proto.settings.SettingsProto.ProfileList.Profile.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MINECRAFTPATH_FIELD_NUMBER = 2;
      private volatile java.lang.Object minecraftPath_;
      /**
       * <code>string minecraftPath = 2;</code>
       */
      public java.lang.String getMinecraftPath() {
        java.lang.Object ref = minecraftPath_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          minecraftPath_ = s;
          return s;
        }
      }
      /**
       * <code>string minecraftPath = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMinecraftPathBytes() {
        java.lang.Object ref = minecraftPath_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          minecraftPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SELECTEDMODPACK_FIELD_NUMBER = 3;
      private volatile java.lang.Object selectedModpack_;
      /**
       * <code>string selectedModpack = 3;</code>
       */
      public java.lang.String getSelectedModpack() {
        java.lang.Object ref = selectedModpack_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectedModpack_ = s;
          return s;
        }
      }
      /**
       * <code>string selectedModpack = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSelectedModpackBytes() {
        java.lang.Object ref = selectedModpack_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectedModpack_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int REPLACE_FIELD_NUMBER = 4;
      private boolean replace_;
      /**
       * <code>bool replace = 4;</code>
       */
      public boolean getReplace() {
        return replace_;
      }

      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.proto.settings.SettingsProto.ProfileList.Profile parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.proto.settings.SettingsProto.ProfileList.Profile prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code modpack.ProfileList.Profile}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:modpack.ProfileList.Profile)
          com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_Profile_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_Profile_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.proto.settings.SettingsProto.ProfileList.Profile.class, com.proto.settings.SettingsProto.ProfileList.Profile.Builder.class);
        }

        // Construct using com.proto.settings.SettingsProto.ProfileList.Profile.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          minecraftPath_ = "";

          selectedModpack_ = "";

          replace_ = false;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_Profile_descriptor;
        }

        @java.lang.Override
        public com.proto.settings.SettingsProto.ProfileList.Profile getDefaultInstanceForType() {
          return com.proto.settings.SettingsProto.ProfileList.Profile.getDefaultInstance();
        }

        @java.lang.Override
        public com.proto.settings.SettingsProto.ProfileList.Profile build() {
          com.proto.settings.SettingsProto.ProfileList.Profile result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.proto.settings.SettingsProto.ProfileList.Profile buildPartial() {
          com.proto.settings.SettingsProto.ProfileList.Profile result = new com.proto.settings.SettingsProto.ProfileList.Profile(this);
          result.name_ = name_;
          result.minecraftPath_ = minecraftPath_;
          result.selectedModpack_ = selectedModpack_;
          result.replace_ = replace_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object minecraftPath_ = "";
        /**
         * <code>string minecraftPath = 2;</code>
         */
        public java.lang.String getMinecraftPath() {
          java.lang.Object ref = minecraftPath_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            minecraftPath_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string minecraftPath = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMinecraftPathBytes() {
          java.lang.Object ref = minecraftPath_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            minecraftPath_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string minecraftPath = 2;</code>
         */
        public Builder setMinecraftPath(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          minecraftPath_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string minecraftPath = 2;</code>
         */
        public Builder clearMinecraftPath() {
          
          minecraftPath_ = getDefaultInstance().getMinecraftPath();
          onChanged();
          return this;
        }
        /**
         * <code>string minecraftPath = 2;</code>
         */
        public Builder setMinecraftPathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          minecraftPath_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object selectedModpack_ = "";
        /**
         * <code>string selectedModpack = 3;</code>
         */
        public java.lang.String getSelectedModpack() {
          java.lang.Object ref = selectedModpack_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            selectedModpack_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string selectedModpack = 3;</code>
         */
        public com.google.protobuf.ByteString
            getSelectedModpackBytes() {
          java.lang.Object ref = selectedModpack_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            selectedModpack_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string selectedModpack = 3;</code>
         */
        public Builder setSelectedModpack(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          selectedModpack_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string selectedModpack = 3;</code>
         */
        public Builder clearSelectedModpack() {
          
          selectedModpack_ = getDefaultInstance().getSelectedModpack();
          onChanged();
          return this;
        }
        /**
         * <code>string selectedModpack = 3;</code>
         */
        public Builder setSelectedModpackBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          selectedModpack_ = value;
          onChanged();
          return this;
        }

        private boolean replace_ ;
        /**
         * <code>bool replace = 4;</code>
         */
        public boolean getReplace() {
          return replace_;
        }
        /**
         * <code>bool replace = 4;</code>
         */
        public Builder setReplace(boolean value) {
          
          replace_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool replace = 4;</code>
         */
        public Builder clearReplace() {
          
          replace_ = false;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:modpack.ProfileList.Profile)
      }

      // @@protoc_insertion_point(class_scope:modpack.ProfileList.Profile)
      private static final com.proto.settings.SettingsProto.ProfileList.Profile DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.proto.settings.SettingsProto.ProfileList.Profile();
      }

      public static com.proto.settings.SettingsProto.ProfileList.Profile getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Profile>
          PARSER = new com.google.protobuf.AbstractParser<Profile>() {
        @java.lang.Override
        public Profile parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(
                    builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Profile> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Profile> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.proto.settings.SettingsProto.ProfileList.Profile getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PROFILES_FIELD_NUMBER = 1;
    private java.util.List<com.proto.settings.SettingsProto.ProfileList.Profile> profiles_;
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    public java.util.List<com.proto.settings.SettingsProto.ProfileList.Profile> getProfilesList() {
      return profiles_;
    }
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    public java.util.List<? extends com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder> 
        getProfilesOrBuilderList() {
      return profiles_;
    }
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    public int getProfilesCount() {
      return profiles_.size();
    }
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    public com.proto.settings.SettingsProto.ProfileList.Profile getProfiles(int index) {
      return profiles_.get(index);
    }
    /**
     * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
     */
    public com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder getProfilesOrBuilder(
        int index) {
      return profiles_.get(index);
    }

    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.settings.SettingsProto.ProfileList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.settings.SettingsProto.ProfileList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code modpack.ProfileList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:modpack.ProfileList)
        com.proto.settings.SettingsProto.ProfileListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.settings.SettingsProto.ProfileList.class, com.proto.settings.SettingsProto.ProfileList.Builder.class);
      }

      // Construct using com.proto.settings.SettingsProto.ProfileList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProfilesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (profilesBuilder_ == null) {
          profiles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          profilesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.settings.SettingsProto.internal_static_modpack_ProfileList_descriptor;
      }

      @java.lang.Override
      public com.proto.settings.SettingsProto.ProfileList getDefaultInstanceForType() {
        return com.proto.settings.SettingsProto.ProfileList.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.settings.SettingsProto.ProfileList build() {
        com.proto.settings.SettingsProto.ProfileList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.settings.SettingsProto.ProfileList buildPartial() {
        com.proto.settings.SettingsProto.ProfileList result = new com.proto.settings.SettingsProto.ProfileList(this);
        int from_bitField0_ = bitField0_;
        if (profilesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            profiles_ = java.util.Collections.unmodifiableList(profiles_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.profiles_ = profiles_;
        } else {
          result.profiles_ = profilesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private java.util.List<com.proto.settings.SettingsProto.ProfileList.Profile> profiles_ =
        java.util.Collections.emptyList();
      private void ensureProfilesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          profiles_ = new java.util.ArrayList<com.proto.settings.SettingsProto.ProfileList.Profile>(profiles_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.settings.SettingsProto.ProfileList.Profile, com.proto.settings.SettingsProto.ProfileList.Profile.Builder, com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder> profilesBuilder_;

      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public java.util.List<com.proto.settings.SettingsProto.ProfileList.Profile> getProfilesList() {
        if (profilesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(profiles_);
        } else {
          return profilesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public int getProfilesCount() {
        if (profilesBuilder_ == null) {
          return profiles_.size();
        } else {
          return profilesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public com.proto.settings.SettingsProto.ProfileList.Profile getProfiles(int index) {
        if (profilesBuilder_ == null) {
          return profiles_.get(index);
        } else {
          return profilesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder setProfiles(
          int index, com.proto.settings.SettingsProto.ProfileList.Profile value) {
        if (profilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfilesIsMutable();
          profiles_.set(index, value);
          onChanged();
        } else {
          profilesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder setProfiles(
          int index, com.proto.settings.SettingsProto.ProfileList.Profile.Builder builderForValue) {
        if (profilesBuilder_ == null) {
          ensureProfilesIsMutable();
          profiles_.set(index, builderForValue.build());
          onChanged();
        } else {
          profilesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder addProfiles(com.proto.settings.SettingsProto.ProfileList.Profile value) {
        if (profilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfilesIsMutable();
          profiles_.add(value);
          onChanged();
        } else {
          profilesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder addProfiles(
          int index, com.proto.settings.SettingsProto.ProfileList.Profile value) {
        if (profilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfilesIsMutable();
          profiles_.add(index, value);
          onChanged();
        } else {
          profilesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder addProfiles(
          com.proto.settings.SettingsProto.ProfileList.Profile.Builder builderForValue) {
        if (profilesBuilder_ == null) {
          ensureProfilesIsMutable();
          profiles_.add(builderForValue.build());
          onChanged();
        } else {
          profilesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder addProfiles(
          int index, com.proto.settings.SettingsProto.ProfileList.Profile.Builder builderForValue) {
        if (profilesBuilder_ == null) {
          ensureProfilesIsMutable();
          profiles_.add(index, builderForValue.build());
          onChanged();
        } else {
          profilesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder addAllProfiles(
          java.lang.Iterable<? extends com.proto.settings.SettingsProto.ProfileList.Profile> values) {
        if (profilesBuilder_ == null) {
          ensureProfilesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, profiles_);
          onChanged();
        } else {
          profilesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder clearProfiles() {
        if (profilesBuilder_ == null) {
          profiles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          profilesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public Builder removeProfiles(int index) {
        if (profilesBuilder_ == null) {
          ensureProfilesIsMutable();
          profiles_.remove(index);
          onChanged();
        } else {
          profilesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public com.proto.settings.SettingsProto.ProfileList.Profile.Builder getProfilesBuilder(
          int index) {
        return getProfilesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder getProfilesOrBuilder(
          int index) {
        if (profilesBuilder_ == null) {
          return profiles_.get(index);  } else {
          return profilesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public java.util.List<? extends com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder> 
           getProfilesOrBuilderList() {
        if (profilesBuilder_ != null) {
          return profilesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(profiles_);
        }
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public com.proto.settings.SettingsProto.ProfileList.Profile.Builder addProfilesBuilder() {
        return getProfilesFieldBuilder().addBuilder(
            com.proto.settings.SettingsProto.ProfileList.Profile.getDefaultInstance());
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public com.proto.settings.SettingsProto.ProfileList.Profile.Builder addProfilesBuilder(
          int index) {
        return getProfilesFieldBuilder().addBuilder(
            index, com.proto.settings.SettingsProto.ProfileList.Profile.getDefaultInstance());
      }
      /**
       * <code>repeated .modpack.ProfileList.Profile profiles = 1;</code>
       */
      public java.util.List<com.proto.settings.SettingsProto.ProfileList.Profile.Builder> 
           getProfilesBuilderList() {
        return getProfilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.settings.SettingsProto.ProfileList.Profile, com.proto.settings.SettingsProto.ProfileList.Profile.Builder, com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder> 
          getProfilesFieldBuilder() {
        if (profilesBuilder_ == null) {
          profilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.proto.settings.SettingsProto.ProfileList.Profile, com.proto.settings.SettingsProto.ProfileList.Profile.Builder, com.proto.settings.SettingsProto.ProfileList.ProfileOrBuilder>(
                  profiles_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          profiles_ = null;
        }
        return profilesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:modpack.ProfileList)
    }

    // @@protoc_insertion_point(class_scope:modpack.ProfileList)
    private static final com.proto.settings.SettingsProto.ProfileList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.settings.SettingsProto.ProfileList();
    }

    public static com.proto.settings.SettingsProto.ProfileList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProfileList>
        PARSER = new com.google.protobuf.AbstractParser<ProfileList>() {
      @java.lang.Override
      public ProfileList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProfileList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProfileList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.settings.SettingsProto.ProfileList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modpack_ProfileList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modpack_ProfileList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modpack_ProfileList_Profile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modpack_ProfileList_Profile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Settings.proto\022\007modpack\"\227\001\n\013ProfileLis" +
      "t\022.\n\010profiles\030\001 \003(\0132\034.modpack.ProfileLis" +
      "t.Profile\032X\n\007Profile\022\014\n\004name\030\001 \001(\t\022\025\n\rmi" +
      "necraftPath\030\002 \001(\t\022\027\n\017selectedModpack\030\003 \001" +
      "(\t\022\017\n\007replace\030\004 \001(\010B%\n\022com.proto.setting" +
      "sB\rSettingsProtoH\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_modpack_ProfileList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_modpack_ProfileList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modpack_ProfileList_descriptor,
        new java.lang.String[] { "Profiles", });
    internal_static_modpack_ProfileList_Profile_descriptor =
      internal_static_modpack_ProfileList_descriptor.getNestedTypes().get(0);
    internal_static_modpack_ProfileList_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modpack_ProfileList_Profile_descriptor,
        new java.lang.String[] { "Name", "MinecraftPath", "SelectedModpack", "Replace", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
