// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Modpack.proto

package com.proto.modpack;

public final class ModpackProto {
  private ModpackProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ModpackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:modpack.Modpack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    java.util.List<com.proto.modpack.ModpackProto.Modpack.Mod> 
        getModsList();
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    com.proto.modpack.ModpackProto.Modpack.Mod getMods(int index);
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    int getModsCount();
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    java.util.List<? extends com.proto.modpack.ModpackProto.Modpack.ModOrBuilder> 
        getModsOrBuilderList();
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    com.proto.modpack.ModpackProto.Modpack.ModOrBuilder getModsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code modpack.Modpack}
   */
  public  static final class Modpack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:modpack.Modpack)
      ModpackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Modpack.newBuilder() to construct.
    private Modpack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Modpack() {
      name_ = "";
      mods_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.modpack.ModpackProto.Modpack.class, com.proto.modpack.ModpackProto.Modpack.Builder.class);
    }

    public interface ModOrBuilder extends
        // @@protoc_insertion_point(interface_extends:modpack.Modpack.Mod)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string url = 1;</code>
       */
      java.lang.String getUrl();
      /**
       * <code>string url = 1;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();

      /**
       * <code>string name = 3;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 3;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string mversion = 4;</code>
       */
      java.lang.String getMversion();
      /**
       * <code>string mversion = 4;</code>
       */
      com.google.protobuf.ByteString
          getMversionBytes();
    }
    /**
     * Protobuf type {@code modpack.Modpack.Mod}
     */
    public  static final class Mod extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:modpack.Modpack.Mod)
        ModOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Mod.newBuilder() to construct.
      private Mod(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Mod() {
        url_ = "";
        name_ = "";
        mversion_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_Mod_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_Mod_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.modpack.ModpackProto.Modpack.Mod.class, com.proto.modpack.ModpackProto.Modpack.Mod.Builder.class);
      }

      public static final int URL_FIELD_NUMBER = 1;
      private volatile java.lang.Object url_;
      /**
       * <code>string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        }
      }
      /**
       * <code>string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MVERSION_FIELD_NUMBER = 4;
      private volatile java.lang.Object mversion_;
      /**
       * <code>string mversion = 4;</code>
       */
      public java.lang.String getMversion() {
        java.lang.Object ref = mversion_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mversion_ = s;
          return s;
        }
      }
      /**
       * <code>string mversion = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMversionBytes() {
        java.lang.Object ref = mversion_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mversion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.proto.modpack.ModpackProto.Modpack.Mod parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.proto.modpack.ModpackProto.Modpack.Mod prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code modpack.Modpack.Mod}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:modpack.Modpack.Mod)
          com.proto.modpack.ModpackProto.Modpack.ModOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_Mod_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_Mod_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.proto.modpack.ModpackProto.Modpack.Mod.class, com.proto.modpack.ModpackProto.Modpack.Mod.Builder.class);
        }

        // Construct using com.proto.modpack.ModpackProto.Modpack.Mod.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          url_ = "";

          name_ = "";

          mversion_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_Mod_descriptor;
        }

        @java.lang.Override
        public com.proto.modpack.ModpackProto.Modpack.Mod getDefaultInstanceForType() {
          return com.proto.modpack.ModpackProto.Modpack.Mod.getDefaultInstance();
        }

        @java.lang.Override
        public com.proto.modpack.ModpackProto.Modpack.Mod build() {
          com.proto.modpack.ModpackProto.Modpack.Mod result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.proto.modpack.ModpackProto.Modpack.Mod buildPartial() {
          com.proto.modpack.ModpackProto.Modpack.Mod result = new com.proto.modpack.ModpackProto.Modpack.Mod(this);
          result.url_ = url_;
          result.name_ = name_;
          result.mversion_ = mversion_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }

        private java.lang.Object url_ = "";
        /**
         * <code>string url = 1;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            url_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string url = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string url = 1;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string url = 1;</code>
         */
        public Builder clearUrl() {
          
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>string url = 1;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          url_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 3;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 3;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 3;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 3;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 3;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object mversion_ = "";
        /**
         * <code>string mversion = 4;</code>
         */
        public java.lang.String getMversion() {
          java.lang.Object ref = mversion_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            mversion_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string mversion = 4;</code>
         */
        public com.google.protobuf.ByteString
            getMversionBytes() {
          java.lang.Object ref = mversion_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            mversion_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string mversion = 4;</code>
         */
        public Builder setMversion(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          mversion_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string mversion = 4;</code>
         */
        public Builder clearMversion() {
          
          mversion_ = getDefaultInstance().getMversion();
          onChanged();
          return this;
        }
        /**
         * <code>string mversion = 4;</code>
         */
        public Builder setMversionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          mversion_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:modpack.Modpack.Mod)
      }

      // @@protoc_insertion_point(class_scope:modpack.Modpack.Mod)
      private static final com.proto.modpack.ModpackProto.Modpack.Mod DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.proto.modpack.ModpackProto.Modpack.Mod();
      }

      public static com.proto.modpack.ModpackProto.Modpack.Mod getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Mod>
          PARSER = new com.google.protobuf.AbstractParser<Mod>() {
        @java.lang.Override
        public Mod parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(
                    builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Mod> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Mod> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.proto.modpack.ModpackProto.Modpack.Mod getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODS_FIELD_NUMBER = 2;
    private java.util.List<com.proto.modpack.ModpackProto.Modpack.Mod> mods_;
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    public java.util.List<com.proto.modpack.ModpackProto.Modpack.Mod> getModsList() {
      return mods_;
    }
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    public java.util.List<? extends com.proto.modpack.ModpackProto.Modpack.ModOrBuilder> 
        getModsOrBuilderList() {
      return mods_;
    }
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    public int getModsCount() {
      return mods_.size();
    }
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    public com.proto.modpack.ModpackProto.Modpack.Mod getMods(int index) {
      return mods_.get(index);
    }
    /**
     * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
     */
    public com.proto.modpack.ModpackProto.Modpack.ModOrBuilder getModsOrBuilder(
        int index) {
      return mods_.get(index);
    }

    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.modpack.ModpackProto.Modpack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.modpack.ModpackProto.Modpack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code modpack.Modpack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:modpack.Modpack)
        com.proto.modpack.ModpackProto.ModpackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.modpack.ModpackProto.Modpack.class, com.proto.modpack.ModpackProto.Modpack.Builder.class);
      }

      // Construct using com.proto.modpack.ModpackProto.Modpack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getModsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (modsBuilder_ == null) {
          mods_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          modsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.modpack.ModpackProto.internal_static_modpack_Modpack_descriptor;
      }

      @java.lang.Override
      public com.proto.modpack.ModpackProto.Modpack getDefaultInstanceForType() {
        return com.proto.modpack.ModpackProto.Modpack.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.modpack.ModpackProto.Modpack build() {
        com.proto.modpack.ModpackProto.Modpack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.modpack.ModpackProto.Modpack buildPartial() {
        com.proto.modpack.ModpackProto.Modpack result = new com.proto.modpack.ModpackProto.Modpack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (modsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            mods_ = java.util.Collections.unmodifiableList(mods_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.mods_ = mods_;
        } else {
          result.mods_ = modsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.proto.modpack.ModpackProto.Modpack.Mod> mods_ =
        java.util.Collections.emptyList();
      private void ensureModsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          mods_ = new java.util.ArrayList<com.proto.modpack.ModpackProto.Modpack.Mod>(mods_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.modpack.ModpackProto.Modpack.Mod, com.proto.modpack.ModpackProto.Modpack.Mod.Builder, com.proto.modpack.ModpackProto.Modpack.ModOrBuilder> modsBuilder_;

      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public java.util.List<com.proto.modpack.ModpackProto.Modpack.Mod> getModsList() {
        if (modsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mods_);
        } else {
          return modsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public int getModsCount() {
        if (modsBuilder_ == null) {
          return mods_.size();
        } else {
          return modsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public com.proto.modpack.ModpackProto.Modpack.Mod getMods(int index) {
        if (modsBuilder_ == null) {
          return mods_.get(index);
        } else {
          return modsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder setMods(
          int index, com.proto.modpack.ModpackProto.Modpack.Mod value) {
        if (modsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModsIsMutable();
          mods_.set(index, value);
          onChanged();
        } else {
          modsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder setMods(
          int index, com.proto.modpack.ModpackProto.Modpack.Mod.Builder builderForValue) {
        if (modsBuilder_ == null) {
          ensureModsIsMutable();
          mods_.set(index, builderForValue.build());
          onChanged();
        } else {
          modsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder addMods(com.proto.modpack.ModpackProto.Modpack.Mod value) {
        if (modsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModsIsMutable();
          mods_.add(value);
          onChanged();
        } else {
          modsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder addMods(
          int index, com.proto.modpack.ModpackProto.Modpack.Mod value) {
        if (modsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModsIsMutable();
          mods_.add(index, value);
          onChanged();
        } else {
          modsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder addMods(
          com.proto.modpack.ModpackProto.Modpack.Mod.Builder builderForValue) {
        if (modsBuilder_ == null) {
          ensureModsIsMutable();
          mods_.add(builderForValue.build());
          onChanged();
        } else {
          modsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder addMods(
          int index, com.proto.modpack.ModpackProto.Modpack.Mod.Builder builderForValue) {
        if (modsBuilder_ == null) {
          ensureModsIsMutable();
          mods_.add(index, builderForValue.build());
          onChanged();
        } else {
          modsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder addAllMods(
          java.lang.Iterable<? extends com.proto.modpack.ModpackProto.Modpack.Mod> values) {
        if (modsBuilder_ == null) {
          ensureModsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mods_);
          onChanged();
        } else {
          modsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder clearMods() {
        if (modsBuilder_ == null) {
          mods_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          modsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public Builder removeMods(int index) {
        if (modsBuilder_ == null) {
          ensureModsIsMutable();
          mods_.remove(index);
          onChanged();
        } else {
          modsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public com.proto.modpack.ModpackProto.Modpack.Mod.Builder getModsBuilder(
          int index) {
        return getModsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public com.proto.modpack.ModpackProto.Modpack.ModOrBuilder getModsOrBuilder(
          int index) {
        if (modsBuilder_ == null) {
          return mods_.get(index);  } else {
          return modsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public java.util.List<? extends com.proto.modpack.ModpackProto.Modpack.ModOrBuilder> 
           getModsOrBuilderList() {
        if (modsBuilder_ != null) {
          return modsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mods_);
        }
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public com.proto.modpack.ModpackProto.Modpack.Mod.Builder addModsBuilder() {
        return getModsFieldBuilder().addBuilder(
            com.proto.modpack.ModpackProto.Modpack.Mod.getDefaultInstance());
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public com.proto.modpack.ModpackProto.Modpack.Mod.Builder addModsBuilder(
          int index) {
        return getModsFieldBuilder().addBuilder(
            index, com.proto.modpack.ModpackProto.Modpack.Mod.getDefaultInstance());
      }
      /**
       * <code>repeated .modpack.Modpack.Mod mods = 2;</code>
       */
      public java.util.List<com.proto.modpack.ModpackProto.Modpack.Mod.Builder> 
           getModsBuilderList() {
        return getModsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.modpack.ModpackProto.Modpack.Mod, com.proto.modpack.ModpackProto.Modpack.Mod.Builder, com.proto.modpack.ModpackProto.Modpack.ModOrBuilder> 
          getModsFieldBuilder() {
        if (modsBuilder_ == null) {
          modsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.proto.modpack.ModpackProto.Modpack.Mod, com.proto.modpack.ModpackProto.Modpack.Mod.Builder, com.proto.modpack.ModpackProto.Modpack.ModOrBuilder>(
                  mods_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          mods_ = null;
        }
        return modsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:modpack.Modpack)
    }

    // @@protoc_insertion_point(class_scope:modpack.Modpack)
    private static final com.proto.modpack.ModpackProto.Modpack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.modpack.ModpackProto.Modpack();
    }

    public static com.proto.modpack.ModpackProto.Modpack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Modpack>
        PARSER = new com.google.protobuf.AbstractParser<Modpack>() {
      @java.lang.Override
      public Modpack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Modpack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Modpack> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.modpack.ModpackProto.Modpack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modpack_Modpack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modpack_Modpack_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modpack_Modpack_Mod_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modpack_Modpack_Mod_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rModpack.proto\022\007modpack\"u\n\007Modpack\022\014\n\004n" +
      "ame\030\001 \001(\t\022\"\n\004mods\030\002 \003(\0132\024.modpack.Modpac" +
      "k.Mod\0328\n\003Mod\022\013\n\003url\030\001 \001(\t\022\014\n\004name\030\003 \001(\t\022" +
      "\020\n\010mversion\030\004 \001(\tJ\004\010\002\020\003B#\n\021com.proto.mod" +
      "packB\014ModpackProtoH\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_modpack_Modpack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_modpack_Modpack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modpack_Modpack_descriptor,
        new java.lang.String[] { "Name", "Mods", });
    internal_static_modpack_Modpack_Mod_descriptor =
      internal_static_modpack_Modpack_descriptor.getNestedTypes().get(0);
    internal_static_modpack_Modpack_Mod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modpack_Modpack_Mod_descriptor,
        new java.lang.String[] { "Url", "Name", "Mversion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
