// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VideoDataMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LocalStreamingService.Objects.Protobuf {

  /// <summary>Holder for reflection information generated from VideoDataMessage.proto</summary>
  public static partial class VideoDataMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for VideoDataMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VideoDataMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZWaWRlb0RhdGFNZXNzYWdlLnByb3RvInYKDVNlcmllc01lc3NhZ2USEwoL",
            "U2VyaWVzSW5kZXgYASABKAUSDQoFVGl0bGUYAiABKAkSFAoMSGlkZUNoaWxk",
            "cmVuGAMgASgIEhMKC0Rlc2NyaXB0aW9uGAQgASgJEhYKDlRodW1ibmFpbFRv",
            "a2VuGAUgASgJIp0BCgtGaWxtTWVzc2FnZRISCgpWaWRlb0luZGV4GAEgASgF",
            "Eg0KBVRpdGxlGAIgASgJEhEKCU1ldGF0aXRsZRgDIAEoCRIQCghTdWJ0aXRs",
            "ZRgEIAEoCRIOCgZMZW5ndGgYBSABKAUSHgoGU2VyaWVzGAYgASgLMg4uU2Vy",
            "aWVzTWVzc2FnZRIWCg5UaHVtYm5haWxUb2tlbhgHIAEoCSI0ChZGaWxtSW5m",
            "b3JtYXRpb25NZXNzYWdlEhoKBEZpbG0YASADKAsyDC5GaWxtTWVzc2FnZSIu",
            "CglGaWxtVG9rZW4SEgoKVmlkZW9JbmRleBgBIAEoBRINCgVUb2tlbhgCIAEo",
            "CSJDCgxFcnJvck1lc3NhZ2USHQoJRXJyb3JUeXBlGAEgASgOMgouRXJyb3JU",
            "eXBlEhQKDEVycm9yTWVzc2FnZRgCIAEoCSpTCglFcnJvclR5cGUSEAoMVW5r",
            "bm93bkVycm9yEAASDwoLU3lzdGVtRXJyb3IQARIPCgtJbmNvcnJlY3RJRBAC",
            "EhIKDlRvb01hbnlSZWNvcmRzEANCKaoCJkxvY2FsU3RyZWFtaW5nU2Vydmlj",
            "ZS5PYmplY3RzLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LocalStreamingService.Objects.Protobuf.ErrorType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LocalStreamingService.Objects.Protobuf.SeriesMessage), global::LocalStreamingService.Objects.Protobuf.SeriesMessage.Parser, new[]{ "SeriesIndex", "Title", "HideChildren", "Description", "ThumbnailToken" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LocalStreamingService.Objects.Protobuf.FilmMessage), global::LocalStreamingService.Objects.Protobuf.FilmMessage.Parser, new[]{ "VideoIndex", "Title", "Metatitle", "Subtitle", "Length", "Series", "ThumbnailToken" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LocalStreamingService.Objects.Protobuf.FilmInformationMessage), global::LocalStreamingService.Objects.Protobuf.FilmInformationMessage.Parser, new[]{ "Film" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LocalStreamingService.Objects.Protobuf.FilmToken), global::LocalStreamingService.Objects.Protobuf.FilmToken.Parser, new[]{ "VideoIndex", "Token" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LocalStreamingService.Objects.Protobuf.ErrorMessage), global::LocalStreamingService.Objects.Protobuf.ErrorMessage.Parser, new[]{ "ErrorType", "ErrorMessage_" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ErrorType {
    [pbr::OriginalName("UnknownError")] UnknownError = 0,
    [pbr::OriginalName("SystemError")] SystemError = 1,
    [pbr::OriginalName("IncorrectID")] IncorrectId = 2,
    [pbr::OriginalName("TooManyRecords")] TooManyRecords = 3,
  }

  #endregion

  #region Messages
  public sealed partial class SeriesMessage : pb::IMessage<SeriesMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeriesMessage> _parser = new pb::MessageParser<SeriesMessage>(() => new SeriesMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeriesMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LocalStreamingService.Objects.Protobuf.VideoDataMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeriesMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeriesMessage(SeriesMessage other) : this() {
      seriesIndex_ = other.seriesIndex_;
      title_ = other.title_;
      hideChildren_ = other.hideChildren_;
      description_ = other.description_;
      thumbnailToken_ = other.thumbnailToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeriesMessage Clone() {
      return new SeriesMessage(this);
    }

    /// <summary>Field number for the "SeriesIndex" field.</summary>
    public const int SeriesIndexFieldNumber = 1;
    private int seriesIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeriesIndex {
      get { return seriesIndex_; }
      set {
        seriesIndex_ = value;
      }
    }

    /// <summary>Field number for the "Title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HideChildren" field.</summary>
    public const int HideChildrenFieldNumber = 3;
    private bool hideChildren_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HideChildren {
      get { return hideChildren_; }
      set {
        hideChildren_ = value;
      }
    }

    /// <summary>Field number for the "Description" field.</summary>
    public const int DescriptionFieldNumber = 4;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ThumbnailToken" field.</summary>
    public const int ThumbnailTokenFieldNumber = 5;
    private string thumbnailToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ThumbnailToken {
      get { return thumbnailToken_; }
      set {
        thumbnailToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeriesMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeriesMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeriesIndex != other.SeriesIndex) return false;
      if (Title != other.Title) return false;
      if (HideChildren != other.HideChildren) return false;
      if (Description != other.Description) return false;
      if (ThumbnailToken != other.ThumbnailToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeriesIndex != 0) hash ^= SeriesIndex.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (HideChildren != false) hash ^= HideChildren.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (ThumbnailToken.Length != 0) hash ^= ThumbnailToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeriesIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeriesIndex);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (HideChildren != false) {
        output.WriteRawTag(24);
        output.WriteBool(HideChildren);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (ThumbnailToken.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ThumbnailToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeriesIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeriesIndex);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (HideChildren != false) {
        output.WriteRawTag(24);
        output.WriteBool(HideChildren);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (ThumbnailToken.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ThumbnailToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeriesIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeriesIndex);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (HideChildren != false) {
        size += 1 + 1;
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (ThumbnailToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ThumbnailToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeriesMessage other) {
      if (other == null) {
        return;
      }
      if (other.SeriesIndex != 0) {
        SeriesIndex = other.SeriesIndex;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.HideChildren != false) {
        HideChildren = other.HideChildren;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.ThumbnailToken.Length != 0) {
        ThumbnailToken = other.ThumbnailToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeriesIndex = input.ReadInt32();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 24: {
            HideChildren = input.ReadBool();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 42: {
            ThumbnailToken = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeriesIndex = input.ReadInt32();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 24: {
            HideChildren = input.ReadBool();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 42: {
            ThumbnailToken = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FilmMessage : pb::IMessage<FilmMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FilmMessage> _parser = new pb::MessageParser<FilmMessage>(() => new FilmMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FilmMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LocalStreamingService.Objects.Protobuf.VideoDataMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmMessage(FilmMessage other) : this() {
      videoIndex_ = other.videoIndex_;
      title_ = other.title_;
      metatitle_ = other.metatitle_;
      subtitle_ = other.subtitle_;
      length_ = other.length_;
      series_ = other.series_ != null ? other.series_.Clone() : null;
      thumbnailToken_ = other.thumbnailToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmMessage Clone() {
      return new FilmMessage(this);
    }

    /// <summary>Field number for the "VideoIndex" field.</summary>
    public const int VideoIndexFieldNumber = 1;
    private int videoIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VideoIndex {
      get { return videoIndex_; }
      set {
        videoIndex_ = value;
      }
    }

    /// <summary>Field number for the "Title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Metatitle" field.</summary>
    public const int MetatitleFieldNumber = 3;
    private string metatitle_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Metatitle {
      get { return metatitle_; }
      set {
        metatitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Subtitle" field.</summary>
    public const int SubtitleFieldNumber = 4;
    private string subtitle_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Subtitle {
      get { return subtitle_; }
      set {
        subtitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Length" field.</summary>
    public const int LengthFieldNumber = 5;
    private int length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    /// <summary>Field number for the "Series" field.</summary>
    public const int SeriesFieldNumber = 6;
    private global::LocalStreamingService.Objects.Protobuf.SeriesMessage series_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LocalStreamingService.Objects.Protobuf.SeriesMessage Series {
      get { return series_; }
      set {
        series_ = value;
      }
    }

    /// <summary>Field number for the "ThumbnailToken" field.</summary>
    public const int ThumbnailTokenFieldNumber = 7;
    private string thumbnailToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ThumbnailToken {
      get { return thumbnailToken_; }
      set {
        thumbnailToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FilmMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FilmMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VideoIndex != other.VideoIndex) return false;
      if (Title != other.Title) return false;
      if (Metatitle != other.Metatitle) return false;
      if (Subtitle != other.Subtitle) return false;
      if (Length != other.Length) return false;
      if (!object.Equals(Series, other.Series)) return false;
      if (ThumbnailToken != other.ThumbnailToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VideoIndex != 0) hash ^= VideoIndex.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Metatitle.Length != 0) hash ^= Metatitle.GetHashCode();
      if (Subtitle.Length != 0) hash ^= Subtitle.GetHashCode();
      if (Length != 0) hash ^= Length.GetHashCode();
      if (series_ != null) hash ^= Series.GetHashCode();
      if (ThumbnailToken.Length != 0) hash ^= ThumbnailToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VideoIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(VideoIndex);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (Metatitle.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Metatitle);
      }
      if (Subtitle.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Subtitle);
      }
      if (Length != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Length);
      }
      if (series_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Series);
      }
      if (ThumbnailToken.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ThumbnailToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VideoIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(VideoIndex);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (Metatitle.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Metatitle);
      }
      if (Subtitle.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Subtitle);
      }
      if (Length != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Length);
      }
      if (series_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Series);
      }
      if (ThumbnailToken.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ThumbnailToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VideoIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VideoIndex);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Metatitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Metatitle);
      }
      if (Subtitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Subtitle);
      }
      if (Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Length);
      }
      if (series_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Series);
      }
      if (ThumbnailToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ThumbnailToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FilmMessage other) {
      if (other == null) {
        return;
      }
      if (other.VideoIndex != 0) {
        VideoIndex = other.VideoIndex;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Metatitle.Length != 0) {
        Metatitle = other.Metatitle;
      }
      if (other.Subtitle.Length != 0) {
        Subtitle = other.Subtitle;
      }
      if (other.Length != 0) {
        Length = other.Length;
      }
      if (other.series_ != null) {
        if (series_ == null) {
          Series = new global::LocalStreamingService.Objects.Protobuf.SeriesMessage();
        }
        Series.MergeFrom(other.Series);
      }
      if (other.ThumbnailToken.Length != 0) {
        ThumbnailToken = other.ThumbnailToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            VideoIndex = input.ReadInt32();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            Metatitle = input.ReadString();
            break;
          }
          case 34: {
            Subtitle = input.ReadString();
            break;
          }
          case 40: {
            Length = input.ReadInt32();
            break;
          }
          case 50: {
            if (series_ == null) {
              Series = new global::LocalStreamingService.Objects.Protobuf.SeriesMessage();
            }
            input.ReadMessage(Series);
            break;
          }
          case 58: {
            ThumbnailToken = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            VideoIndex = input.ReadInt32();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            Metatitle = input.ReadString();
            break;
          }
          case 34: {
            Subtitle = input.ReadString();
            break;
          }
          case 40: {
            Length = input.ReadInt32();
            break;
          }
          case 50: {
            if (series_ == null) {
              Series = new global::LocalStreamingService.Objects.Protobuf.SeriesMessage();
            }
            input.ReadMessage(Series);
            break;
          }
          case 58: {
            ThumbnailToken = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FilmInformationMessage : pb::IMessage<FilmInformationMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FilmInformationMessage> _parser = new pb::MessageParser<FilmInformationMessage>(() => new FilmInformationMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FilmInformationMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LocalStreamingService.Objects.Protobuf.VideoDataMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmInformationMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmInformationMessage(FilmInformationMessage other) : this() {
      film_ = other.film_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmInformationMessage Clone() {
      return new FilmInformationMessage(this);
    }

    /// <summary>Field number for the "Film" field.</summary>
    public const int FilmFieldNumber = 1;
    private static readonly pb::FieldCodec<global::LocalStreamingService.Objects.Protobuf.FilmMessage> _repeated_film_codec
        = pb::FieldCodec.ForMessage(10, global::LocalStreamingService.Objects.Protobuf.FilmMessage.Parser);
    private readonly pbc::RepeatedField<global::LocalStreamingService.Objects.Protobuf.FilmMessage> film_ = new pbc::RepeatedField<global::LocalStreamingService.Objects.Protobuf.FilmMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::LocalStreamingService.Objects.Protobuf.FilmMessage> Film {
      get { return film_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FilmInformationMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FilmInformationMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!film_.Equals(other.film_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= film_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      film_.WriteTo(output, _repeated_film_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      film_.WriteTo(ref output, _repeated_film_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += film_.CalculateSize(_repeated_film_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FilmInformationMessage other) {
      if (other == null) {
        return;
      }
      film_.Add(other.film_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            film_.AddEntriesFrom(input, _repeated_film_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            film_.AddEntriesFrom(ref input, _repeated_film_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FilmToken : pb::IMessage<FilmToken>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FilmToken> _parser = new pb::MessageParser<FilmToken>(() => new FilmToken());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FilmToken> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LocalStreamingService.Objects.Protobuf.VideoDataMessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmToken() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmToken(FilmToken other) : this() {
      videoIndex_ = other.videoIndex_;
      token_ = other.token_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilmToken Clone() {
      return new FilmToken(this);
    }

    /// <summary>Field number for the "VideoIndex" field.</summary>
    public const int VideoIndexFieldNumber = 1;
    private int videoIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VideoIndex {
      get { return videoIndex_; }
      set {
        videoIndex_ = value;
      }
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 2;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FilmToken);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FilmToken other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VideoIndex != other.VideoIndex) return false;
      if (Token != other.Token) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VideoIndex != 0) hash ^= VideoIndex.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VideoIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(VideoIndex);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VideoIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(VideoIndex);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VideoIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VideoIndex);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FilmToken other) {
      if (other == null) {
        return;
      }
      if (other.VideoIndex != 0) {
        VideoIndex = other.VideoIndex;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            VideoIndex = input.ReadInt32();
            break;
          }
          case 18: {
            Token = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            VideoIndex = input.ReadInt32();
            break;
          }
          case 18: {
            Token = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ErrorMessage : pb::IMessage<ErrorMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ErrorMessage> _parser = new pb::MessageParser<ErrorMessage>(() => new ErrorMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ErrorMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LocalStreamingService.Objects.Protobuf.VideoDataMessageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorMessage(ErrorMessage other) : this() {
      errorType_ = other.errorType_;
      errorMessage_ = other.errorMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorMessage Clone() {
      return new ErrorMessage(this);
    }

    /// <summary>Field number for the "ErrorType" field.</summary>
    public const int ErrorTypeFieldNumber = 1;
    private global::LocalStreamingService.Objects.Protobuf.ErrorType errorType_ = global::LocalStreamingService.Objects.Protobuf.ErrorType.UnknownError;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LocalStreamingService.Objects.Protobuf.ErrorType ErrorType {
      get { return errorType_; }
      set {
        errorType_ = value;
      }
    }

    /// <summary>Field number for the "ErrorMessage" field.</summary>
    public const int ErrorMessage_FieldNumber = 2;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage_ {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ErrorMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ErrorMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorType != other.ErrorType) return false;
      if (ErrorMessage_ != other.ErrorMessage_) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorType != global::LocalStreamingService.Objects.Protobuf.ErrorType.UnknownError) hash ^= ErrorType.GetHashCode();
      if (ErrorMessage_.Length != 0) hash ^= ErrorMessage_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorType != global::LocalStreamingService.Objects.Protobuf.ErrorType.UnknownError) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorType);
      }
      if (ErrorMessage_.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorType != global::LocalStreamingService.Objects.Protobuf.ErrorType.UnknownError) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorType);
      }
      if (ErrorMessage_.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorType != global::LocalStreamingService.Objects.Protobuf.ErrorType.UnknownError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorType);
      }
      if (ErrorMessage_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage_);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ErrorMessage other) {
      if (other == null) {
        return;
      }
      if (other.ErrorType != global::LocalStreamingService.Objects.Protobuf.ErrorType.UnknownError) {
        ErrorType = other.ErrorType;
      }
      if (other.ErrorMessage_.Length != 0) {
        ErrorMessage_ = other.ErrorMessage_;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorType = (global::LocalStreamingService.Objects.Protobuf.ErrorType) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorMessage_ = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorType = (global::LocalStreamingService.Objects.Protobuf.ErrorType) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorMessage_ = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
